# File: .github/workflows/refresh.yml
name: Refresh

on:
  schedule:
    - cron: "0 3 * * *" # Runs every day at 3am

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - name: Trigger GitHub Pages rebuild
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/CogSysLab/nu-csl/actions/workflows/jekyll.yml/dispatches \
            -d '{"ref":"main"}'
